project_id = "mgqvvvlkgpioikeebgln"

[functions.midtrans-webhook]
verify_jwt = false

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.send-daily-summary]
verify_jwt = false

[functions.create-qris-payment]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = true

[functions.doku-webhook]
verify_jwt = false
